version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: userDB
    volumes:
      - mongo_data:/data/db

  backend:
    image: kubernetes-form-backend:02  
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/userDB
      JWT_SECRET: yourSuperSecretKey
      PORT: 5000

  frontend:
    image: kubernetes-form-frontend:02  
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000  
volumes:
  mongo_data:
