name: Three-Tier CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd frontend
          if ! npm list react-router-dom > /dev/null 2>&1; then npm install react-router-dom; fi
          npm ci
      - name: Build frontend
        run: cd frontend && npm run build --if-present
      - name: Run tests
        run: cd frontend && npm test --if-present

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd backend
          if [ ! -f package-lock.json ]; then npm install --package-lock-only; fi
          npm install
      - name: Build backend
        run: cd backend && npm run build --if-present
      - name: Run tests
        run: cd backend && npm test --if-present
